spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/hackathon_db
    username: postgres
    password: 231429


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true